import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src: [
    {
      path: "../../public/Inter/Inter-VariableFont_opsz,wght.ttf",
      style: "normal",
    },
    {
      path: "../../public/Inter/Inter-Italic-VariableFont_opsz,wght.ttf",
      style: "italic",
    },
  ],
  display: "swap",
  variable: "--font-inter",
});

const notoSansThai = localFont({
  src: "../../public/Noto_Sans_Thai/NotoSansThai-VariableFont_wdth,wght.ttf",
  display: "swap",
  variable: "--font-noto-sans-thai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import StyledComponentsRegistry from "@/lib/antd";
import QueryProvider from "@/lib/query";

import { App, ConfigProvider } from "antd";
import { AuthProvider } from "@/contexts/AuthContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${notoSansThai.variable} antialiased`}
      >
        <QueryProvider>
          <StyledComponentsRegistry>
            <ConfigProvider
              theme={{
                token: {
                  fontFamily: `var(--font-inter), var(--font-noto-sans-thai), sans-serif`,
                },
              }}
            >
              <AuthProvider>
                <App>{children}</App>
              </AuthProvider>
            </ConfigProvider>
          </StyledComponentsRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
